# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('project_link', models.CharField(blank=True, max_length=255, null=True)),
                ('project_picture', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('project_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
