# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_personal_information_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_description',
            field=models.TextField(null=True),
        ),
    ]
